---
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      minor-actions-dependencies:
        # GitHub Actions: Only group minor and patch updates (we want to carefully review major updates)
        update-types: [minor, patch]
