image: nixos/unstable
sources:
  - https://git.alanpearce.eu/nix-packages
secrets:
  - 5a04c7f9-bba4-40ab-b54c-a2daae2989e8
environment:
  NIX_CONFIG: |
    experimental-features = nix-command flakes
    extra-substituters = https://binarycache.alanpearce.eu
    extra-trusted-public-keys = binarycache.alanpearce.eu:ZwqO3XMuajPictjwih8OY2+RXnOKpjZEZFHJjGSxAI4=
  SSH_KNOWN_HOSTS: |
    linde.alanpearce.eu ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHHdh3J7dEmh9G+CVmzFEC8/ont35ZXpCFcpLUO863vC
repositories:
  nixpkgs: https://nixos.org/channels/nixpkgs-unstable
tasks:
  - ssh_config: |
      echo $SSH_KNOWN_HOSTS >> ~/.ssh/known_hosts
  - nixpkgs: |
      nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'

  - build: |
      nix shell -f '<nixpkgs>' nix-build-uncached -c nix-build-uncached nix-packages/ci.nix -A cacheOutputs

  - push-cache: |
      nix copy --substitute-on-destination \
        --to ssh://nixremote@linde.alanpearce.eu \
        ./nix-packages
